### PR TITLE
Fix setting of HSL values from hexa input

### PR DESCRIPTION
**Pull request by bytesnz**
I noticed there was an issue setting the saturation and lightness values when a hexa value is input into the hexa input when the color format was set to HSL.

Simple fix of changing `setHexa()` to use `updateHSX()` instead of `RGBtoHSV()`.

### CODE REVIEW

**Comment by bsmth** [comment]
Hi @bytesnz - thanks a lot for the submission, I don't see the difference with the changes. Would you mind adding some steps to reproduce so I can follow along?

Thanks a lot! :)

**Comment by bytesnz** [comment]
Took a bit to figure out/remember what the problem was. 

When you change the hex value in the input box, the lightness value doesn't get updated

image


To replicate:
1. Change the HSL values to 350 98 80
2. Change the hex value to #4B000D

Observed:
- Hue and saturation change, but lightness does not

Expected:
    - HSL should now be 161 81 54

**Comment by bytesnz** [comment]
Code has been updated since I committed, so there is a conflict now. Will update it.

**Comment by bsmth** [comment]
Thanks a lot for coming back to it and giving some context. I'll wait for your updates re: merge conflict, feel free to ping me for a look when you're ready

**Comment by bytesnz** [comment]
Merged :slightly_smiling_face:

**Comment by bsmth** [comment]
Thanks @bytesnz - I'm going to take a look again shortly

**Review by bsmth — APPROVED** [review]
Very good, tnx, I tested with:

* `#8471BB`
* `#805BEF`
* `#000000`
* `#FF0000`

And I can confirm the Lightness value is being updated properly.

Thank you @bytesnz for your fix - I'm glad it could land eventually :)

**Comment by bytesnz** [comment]
Awesome. Thanks @bsmth :tada:

**Pull request merged**
