### PR TITLE
feat(css): add color-mix() tool

### PR DESCRIPTION
**Pull request by OnkarRuikar**
- related to https://github.com/mdn/content/pull/34371

The PR adds a tool to experiment with the CSS `color-mix()` function. Following is the screenshot of the tool:

### CODE REVIEW

**Comment by bsmth** [comment]
Thanks, @OnkarRuikar. Looking good! I made some suggestions on a branch, do you want to have a look here:

https://github.com/OnkarRuikar/css-examples/compare/css_color_mix...bsmth:css-examples:css_color_mix_brian?expand=1

* monospace font for readability of the `<label>`s.
* Change event listeners to use `input` so we have faster feedback
* Flex for alignment
* Some margin to give the calc / output some breathing room

**Comment by bsmth** [comment]
And just general question; why do we want to include Pickr? Not a blocker, just curious 🤔

**Comment by OnkarRuikar** [comment]
I've applied the changes.

> And just a general question; why do we want to include Pickr?

Because [HTML color input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) doesn't support alpha(transparency) channel: https://github.com/whatwg/html/issues/3400#issuecomment-606737019 .

**Comment by bsmth** [comment]
> I've applied the changes.

Nice, taking a look again!

> > And just a general question; why do we want to include Pickr?
> 
> Because [HTML color input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) doesn't support alpha(transparency) channel: [whatwg/html#3400 (comment)](https://github.com/whatwg/html/issues/3400#issuecomment-606737019) .

Ah-ha, thanks for the hint 👍🏻

**Review by bsmth — APPROVED** [review]
LGTM, only last thing to think about is demonstrating that the percentage doesn't have to be a whole number;

```html
<input id="percentage-one" type="range" name="percent1" step="0.1" />
```

What do you think? I'm fine with merging as-is!

**Comment by OnkarRuikar** [comment]
> LGTM, only last thing to think about is demonstrating that the percentage doesn't have to be a whole number;

:nerd_face: done.

**Comment by bsmth** [comment]
Merging now, thank you!

**Pull request merged**
